### ISSUE TITLE
Function "length" doesn't seem to exist

### ISSUE THREAD

**Issue by ejflick** [technomancy/fennel-lang.org#14]
In the reference pages, it mentions the `length` method. Trying this with the latest version of Fennel(0.2.1-2) installed from luarocks gives:
```
>> (length "3")
[string "return length("3")"]:1: attempt to call a nil value (global 'length')
```

It should be removed from the documentation if it's an unreleased feature.

**Comment by technomancy** [comment]
Oops; I accidentally upgraded the Fennel submodule so this was rendering
the master branch instead of the stable release. Just pushed a fix.
