### ISSUE TITLE
Scope issue in fennel-lang.org repl?

### ISSUE THREAD

**Issue by ergodicbreak** [technomancy/fennel-lang.org#21]
(Moved from https://github.com/bakpakin/Fennel/issues/243)

Hi, I ran into confusing output in the fennel-lang.org repl:

    Welcome to Fennel 0.3.2, running on Fengari (Lua 5.3)

    You can run any Fennel code here; try this: (print "Hello world!")

    (local tbl [[] [] []])

    (var foo (. tbl 1))

    (set foo nil)
    Compile error in 'set' unknown:1: expected local var foo

From help in IRC this sounds like something peculiar to the fennel-lang.org repl.

**Comment by technomancy** [comment]
Thanks to @jaawerth for finding the root cause; this was a problem due to trying to compile the input without the surrounding scope in order to display it in the "Show Lua" pane.
