### ISSUE TITLE
[style request] background color of code blocks

### ISSUE THREAD

**Issue by uvtc** [technomancy/fennel-lang.org#23]
Reading through the documentation on fennel-lang.org, I find it easier to read if the code blocks have a different background color, to distinguish them from the surrounding text.

**Comment by uvtc** [comment]
Ooof. Sorry, nvm. :)

**Comment by technomancy** [comment]
I think this is a pretty good point; why did you close the issue?

**Comment by uvtc** [comment]
I looked at it again and thought it was probably more of a personal preference issue where you'd already chose what you thought was nice. I do think a different background color, and maybe even a slight border, would make it easier to differentiate the code blocks while reading. (While reading, I tend to "shift gears" when I come to a code block, and I think it makes sense for the doc styling to change gears as well (with a box, change in background color).

Some examples of how other langs do it:

  * [the Rust book goes simple light gray](https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html)
  * [Python uses green](https://docs.python.org/3/tutorial/controlflow.html)
  * [MDN uses a gray background with left border](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Functions)
  * [Raku a pinkish-gray](https://docs.raku.org/language/iterating)

**Comment by uvtc** [comment]
Chicken Scheme uses a [light yolk-colored background](http://wiki.call-cc.org/man/5/Deviations%20from%20the%20standard) :), and, as an aside, they have some added magic that highlights matching brackets when you hover over them.

**Comment by uvtc** [comment]
It may also benefit [the setup guide](https://fennel-lang.org/setup) to have two differently-styled blocks: one for commands you're to type into the shell, and another for the fennel code blocks.

Here's an example of this sort of style: <http://mij.oltrelinux.com/devel/autoconf-automake/>

**Comment by technomancy** [comment]
Knocked this one out: https://git.sr.ht/~technomancy/fennel-lang.org/commit/876ff60ac0279ed0e87799a1ef35525c5dd358f6

**Comment by uvtc** [comment]
Nice!
