### ISSUE TITLE
Conference

### ISSUE THREAD

**Issue by technomancy** [technomancy/fennel-lang.org#6]
We've been talking on IRC about having a very low-key 1-day conference in spring of 2019 in Portland where we already have 4 Fennel users. @bakpakin if that's something you'd be up for it would be really cool to have you come but IIRC it's the wrong coast for you so it might be a bit tricky. Anyway wanted to let folks know and gather input.

https://conf.fennel-lang.org/2019

**Comment by bakpakin** [comment]
Wow, that’s really cool! I might be unable to come mostly because of classes, but I’d definitely come if I could make it work. Although it’s hard to know this far in advance, I could probably come on a weekend.

If a few people could come that would be so awesome! I’ll get on irc later because I’m traveling rn, but we can definitely talk there.

**Comment by technomancy** [comment]
I was thinking we'd hold it on a Saturday... if there's a weekend in late March or April that works better for you we can probably schedule it then.

**Comment by technomancy** [comment]
@bakpakin is it too early for you to know a date that would work for you to come out for this? We had someone secure space for a small group in Portland over a weekend. Had some folks asking about the date so it might be nice to nail down, at least tentatively.

**Comment by bakpakin** [comment]
I think late March would be good. Perhaps the 16th? It would be easier for me to come as that's the tail end of my spring break.

**Comment by technomancy** [comment]
Cool; we will plan on the 16th if you're still good with that. @noisesmith has secured a location with A/V as long as we don't have more than a dozen attendees. @bakpakin I can save a slot for you to speak if you want but there's no pressure either way.

**Comment by noisesmith** [comment]
I officially confirmed the space - Central Office downtown Portland location (co-working space). Room for 12 people plus an A/V setup for streaming. We might have other options here if the attendee list gets larger, but otherwise this is confirmed.

**Comment by technomancy** [comment]
Closing this on out as the date has been finalized and the location secured; thanks!
